package handler

import (
	"bytes"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/csv"
	"encoding/hex"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/sorolens/sorolens/apps/api/internal/store"
)

// Requested export formats.
const (
	reportFormatJSON = "json"
	reportFormatCSV  = "csv"
	reportFormatPDF  = "pdf"
)

// ReportSigningKey is the HMAC key used to sign exported reports. Empty is
// allowed: reports are then emitted unsigned and every response says so,
// rather than implying an integrity guarantee that is not there.
type contractReportResponse struct {
	store.MonthlySLA
	// Signed is false when no signing key is configured.
	Signed bool `json:"signed"`
	// Signature is a hex HMAC-SHA256 over the canonical report text, empty when
	// unsigned.
	Signature string `json:"signature,omitempty"`
	// SignatureAlgorithm names the scheme so a verifier does not have to guess.
	SignatureAlgorithm string `json:"signature_algorithm,omitempty"`
	// TLSCheckInterval is the sampling cadence a check represents, exposed so a
	// consumer can convert MTTR in checks into wall-clock time.
	SamplingNote string `json:"sampling_note,omitempty"`
}

// ---- helpers ---------------------------------------------------------------

// reportsSigningKey resolves the signing key, preferring the value wired onto
// the Handler and falling back to the environment so the endpoint works
// without a change to the composition root.
func (h *Handler) reportsSigningKey() []byte {
	if h.ReportSigningKey != "" {
		return []byte(h.ReportSigningKey)
	}
	return []byte(os.Getenv("REPORT_SIGNING_KEY"))
}

// signReport returns a hex HMAC-SHA256 of payload, or "" when no key is set.
//
// HMAC (rather than a raw hash) is the right primitive here: the report is
// generated by this service and verified by a third party, and HMAC proves it
// came from a holder of the key without needing asymmetric key distribution.
func signReport(key, payload []byte) string {
	if len(key) == 0 {
		return ""
	}
	mac := hmac.New(sha256.New, key)
	mac.Write(payload)
	return hex.EncodeToString(mac.Sum(nil))
}

// slaStore resolves the reporting store. Reports are only meaningful when the
// watchdog data is queryable, so an absent implementation is reported as
// "not supported by this deployment" instead of an empty report that looks
// like a real outage.
func (h *Handler) slaStore() (store.SLAStore, bool) {
	s, ok := h.Store.(store.SLAStore)
	return s, ok
}

// reportMonth resolves and validates the ?month= parameter, defaulting to the
// current UTC month.
func reportMonth(raw string) (string, time.Time, time.Time, error) {
	month := raw
	if month == "" {
		month = store.CurrentMonth(time.Now())
	}
	from, to, err := store.MonthRange(month)
	if err != nil {
		return "", time.Time{}, time.Time{}, err
	}
	return month, from, to, nil
}

// loadSLA fetches the month's raw data and computes the report.
func (h *Handler) loadSLA(r *http.Request, contractID, month string, from, to time.Time) (store.MonthlySLA, error) {
	s, ok := h.slaStore()
	if !ok {
		return store.MonthlySLA{}, errSLANotSupported
	}
	checks, err := s.ListHealthChecksInRange(r.Context(), contractID, from, to)
	if err != nil {
		return store.MonthlySLA{}, err
	}
	alerts, err := s.ListAlertsInRange(r.Context(), contractID, from, to)
	if err != nil {
		return store.MonthlySLA{}, err
	}
	return store.ComputeMonthlySLA(contractID, month, checks, alerts), nil
}

var errSLANotSupported = fmt.Errorf("sla reporting is not supported by this deployment")

// ---- handlers --------------------------------------------------------------

// GetContractReport handles
// GET /api/v1/reports/{contract_id}?month=YYYY-MM&format=json|csv|pdf.
//
// Every format is generated from one computed report and one canonical text
// rendering, so the CSV, the PDF and the JSON can never disagree about the
// numbers, and a single signature covers all three.
func (h *Handler) GetContractReport(w http.ResponseWriter, r *http.Request) {
	contractID := chi.URLParam(r, "contract_id")

	format := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("format")))
	if format == "" {
		format = reportFormatJSON
	}
	switch format {
	case reportFormatJSON, reportFormatCSV, reportFormatPDF:
	default:
		writeError(w, r, http.StatusUnprocessableEntity, CodeInvalidInput,
			"format must be one of: json, csv, pdf")
		return
	}

	month, from, to, err := reportMonth(r.URL.Query().Get("month"))
	if err != nil {
		writeError(w, r, http.StatusUnprocessableEntity, CodeInvalidInput, "month must be formatted YYYY-MM")
		return
	}

	rep, err := h.loadSLA(r, contractID, month, from, to)
	if err != nil {
		if err == errSLANotSupported {
			writeError(w, r, http.StatusNotImplemented, CodeInternal, err.Error())
			return
		}
		h.Logger.Error("contract report", "contract_id", contractID, "month", month, "err", err)
		writeError(w, r, http.StatusInternalServerError, CodeInternal, "failed to build contract report")
		return
	}

	// Canonical signed payload: identical for every export format.
	canonical := renderReportText(rep)
	signature := signReport(h.reportsSigningKey(), []byte(canonical))
	signed := signature != ""

	// The signature travels in a header for every format so a caller can verify
	// without parsing the body.
	w.Header().Set("X-Report-Signature-Algorithm", "HMAC-SHA256")
	if signed {
		w.Header().Set("X-Report-Signature", signature)
		w.Header().Set("X-Report-Signed", "true")
	} else {
		w.Header().Set("X-Report-Signed", "false")
	}

	switch format {
	case reportFormatJSON:
		writeJSON(w, http.StatusOK, contractReportResponse{
			MonthlySLA:         rep,
			Signed:             signed,
			Signature:          signature,
			SignatureAlgorithm: "HMAC-SHA256",
			SamplingNote:       "uptime and MTTR are derived from watchdog health-check samples",
		})

	case reportFormatCSV:
		body, err := renderReportCSV(rep)
		if err != nil {
			h.Logger.Error("render report csv", "err", err)
			writeError(w, r, http.StatusInternalServerError, CodeInternal, "failed to render CSV")
			return
		}
		w.Header().Set("Content-Type", "text/csv; charset=utf-8")
		w.Header().Set("Content-Disposition",
			fmt.Sprintf("attachment; filename=%q", reportFilename(contractID, month, "csv")))
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(body)

	case reportFormatPDF:
		body, err := renderReportPDF(rep, signature)
		if err != nil {
			h.Logger.Error("render report pdf", "err", err)
			writeError(w, r, http.StatusInternalServerError, CodeInternal, "failed to render PDF")
			return
		}
		w.Header().Set("Content-Type", "application/pdf")
		w.Header().Set("Content-Disposition",
			fmt.Sprintf("attachment; filename=%q", reportFilename(contractID, month, "pdf")))
		w.Header().Set("Content-Length", strconv.Itoa(len(body)))
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(body)
	}
}

// GetContractSLABadge handles GET /api/v1/reports/{contract_id}/badge.svg.
//
// Returns an embeddable SVG so a contract's month can be shown in a README or
// status page without a client library.
func (h *Handler) GetContractSLABadge(w http.ResponseWriter, r *http.Request) {
	contractID := chi.URLParam(r, "contract_id")

	month, from, to, err := reportMonth(r.URL.Query().Get("month"))
	if err != nil {
		writeError(w, r, http.StatusUnprocessableEntity, CodeInvalidInput, "month must be formatted YYYY-MM")
		return
	}

	rep, err := h.loadSLA(r, contractID, month, from, to)
	if err != nil {
		if err == errSLANotSupported {
			writeError(w, r, http.StatusNotImplemented, CodeInternal, err.Error())
			return
		}
		h.Logger.Error("sla badge", "contract_id", contractID, "month", month, "err", err)
		writeError(w, r, http.StatusInternalServerError, CodeInternal, "failed to build SLA badge")
		return
	}

	svg := renderSLABadge(rep)
	w.Header().Set("Content-Type", "image/svg+xml; charset=utf-8")
	// Badges are embedded in third-party pages: allow long caching but let it
	// expire so a closed month eventually settles. The current month changes,
	// so it is capped at a short TTL.
	w.Header().Set("Cache-Control", badgeCacheControl(month))
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(svg))
}

func badgeCacheControl(month string) string {
	if month == store.CurrentMonth(time.Now()) {
		return "public, max-age=300"
	}
	return "public, max-age=86400"
}

// ---- rendering -------------------------------------------------------------

func reportFilename(contractID, month, ext string) string {
	// Contract ids are 56-char strkeys; the tail is enough to identify one and
	// keeps the filename usable.
	short := contractID
	if len(short) > 11 {
		short = short[:11]
	}
	return fmt.Sprintf("sorolens-sla-%s-%s.%s", short, month, ext)
}

// renderReportText is the canonical, format-independent rendering of a report.
// It is what the signature covers, so verifying a PDF signature and verifying a
// CSV signature are the same operation.
func renderReportText(m store.MonthlySLA) string {
	var b strings.Builder
	fmt.Fprintf(&b, "contract_id=%s\n", m.ContractID)
	fmt.Fprintf(&b, "month=%s\n", m.Month)
	fmt.Fprintf(&b, "uptime_pct=%.4f\n", m.UptimePct)
	fmt.Fprintf(&b, "total_checks=%d\n", m.TotalChecks)
	fmt.Fprintf(&b, "healthy_checks=%d\n", m.HealthyChecks)
	fmt.Fprintf(&b, "incidents=%d\n", m.Incidents)
	fmt.Fprintf(&b, "mttr_seconds=%.2f\n", m.MTTRSeconds)
	fmt.Fprintf(&b, "total_downtime_seconds=%.2f\n", m.TotalDowntimeSeconds)
	fmt.Fprintf(&b, "longest_outage_seconds=%.2f\n", m.LongestOutageSeconds)
	fmt.Fprintf(&b, "ongoing_outage=%t\n", m.OngoingOutage)
	fmt.Fprintf(&b, "critical_alerts=%d\n", m.CriticalAlerts)
	fmt.Fprintf(&b, "warning_alerts=%d\n", m.WarningAlerts)
	fmt.Fprintf(&b, "info_alerts=%d\n", m.InfoAlerts)
	fmt.Fprintf(&b, "total_alerts=%d\n", m.TotalAlerts)
	fmt.Fprintf(&b, "first_check=%s\n", formatTimePtr(m.FirstCheck))
	fmt.Fprintf(&b, "last_check=%s\n", formatTimePtr(m.LastCheck))
	return b.String()
}

// renderReportCSV emits the report as metric,value rows, one per line. A
// key/value shape survives spreadsheet round-trips without the column-ordering
// surprises a wide table brings.
func renderReportCSV(m store.MonthlySLA) ([]byte, error) {
	rows := [][]string{
		{"metric", "value"},
		{"contract_id", m.ContractID},
		{"month", m.Month},
		{"uptime_pct", strconv.FormatFloat(m.UptimePct, 'f', 4, 64)},
		{"total_checks", strconv.FormatInt(m.TotalChecks, 10)},
		{"healthy_checks", strconv.FormatInt(m.HealthyChecks, 10)},
		{"incidents", strconv.FormatInt(m.Incidents, 10)},
		{"mttr_seconds", strconv.FormatFloat(m.MTTRSeconds, 'f', 2, 64)},
		{"total_downtime_seconds", strconv.FormatFloat(m.TotalDowntimeSeconds, 'f', 2, 64)},
		{"longest_outage_seconds", strconv.FormatFloat(m.LongestOutageSeconds, 'f', 2, 64)},
		{"ongoing_outage", strconv.FormatBool(m.OngoingOutage)},
		{"critical_alerts", strconv.FormatInt(m.CriticalAlerts, 10)},
		{"warning_alerts", strconv.FormatInt(m.WarningAlerts, 10)},
		{"info_alerts", strconv.FormatInt(m.InfoAlerts, 10)},
		{"total_alerts", strconv.FormatInt(m.TotalAlerts, 10)},
		{"first_check", formatTimePtr(m.FirstCheck)},
		{"last_check", formatTimePtr(m.LastCheck)},
	}

	var buf bytes.Buffer
	cw := csv.NewWriter(&buf)
	for _, row := range rows {
		if err := cw.Write(row); err != nil {
			return nil, err
		}
	}
	cw.Flush()
	if err := cw.Error(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// renderReportPDF lays the report out as a text table and embeds the signature
// in both the visible footer and the document's Info dictionary.
func renderReportPDF(m store.MonthlySLA, signature string) ([]byte, error) {
	doc := newPDFDoc(fmt.Sprintf("Sorolens SLA report %s %s", m.ContractID, m.Month))

	lines := []string{
		"Sorolens — SLA report",
		"",
		fmt.Sprintf("Contract     %s", m.ContractID),
		fmt.Sprintf("Period       %s (UTC)", m.Month),
		"",
		"Availability",
		fmt.Sprintf("  Uptime       %.4f%%", m.UptimePct),
		fmt.Sprintf("  Checks       %d healthy of %d", m.HealthyChecks, m.TotalChecks),
		fmt.Sprintf("  Verdict      %s", slaVerdict(m)),
		"",
		"Incidents",
		fmt.Sprintf("  Incidents    %d", m.Incidents),
		fmt.Sprintf("  MTTR         %s", formatSeconds(m.MTTRSeconds)),
		fmt.Sprintf("  Downtime     %s", formatSeconds(m.TotalDowntimeSeconds)),
		fmt.Sprintf("  Longest      %s", formatSeconds(m.LongestOutageSeconds)),
		fmt.Sprintf("  Ongoing      %t", m.OngoingOutage),
		"",
		"Alerts",
		fmt.Sprintf("  Critical     %d", m.CriticalAlerts),
		fmt.Sprintf("  Warning      %d", m.WarningAlerts),
		fmt.Sprintf("  Info         %d", m.InfoAlerts),
		fmt.Sprintf("  Total        %d", m.TotalAlerts),
		"",
		"Coverage",
		fmt.Sprintf("  First check  %s", formatTimePtr(m.FirstCheck)),
		fmt.Sprintf("  Last check   %s", formatTimePtr(m.LastCheck)),
		"",
		"Integrity",
		"  Algorithm    HMAC-SHA256",
	}

	if signature == "" {
		lines = append(lines,
			"  Signature    UNSIGNED — set REPORT_SIGNING_KEY to sign exports",
		)
	} else {
		lines = append(lines,
			"  Signature    "+signature[:min(16, len(signature))]+"...",
			"  (full value in the document Info dictionary and the",
			"   X-Report-Signature response header)",
		)
	}
	doc.SetKeywords("HMAC-SHA256 " + signature)

	doc.AddLines(lines)
	return doc.Bytes(), nil
}

// renderSLABadge renders a shields-style SVG badge for a month's uptime.
func renderSLABadge(m store.MonthlySLA) string {
	label := "SLA " + m.Month
	value := "no data"
	if m.HasData() {
		value = fmt.Sprintf("%.3f%%", m.UptimePct)
	}

	color := "#9ca3af" // grey: no data
	if m.HasData() {
		switch {
		case m.UptimePct >= 99.9:
			color = "#2ea44f" // green: three nines met
		case m.UptimePct >= 99.0:
			color = "#d29922" // amber: at risk
		default:
			color = "#d73a49" // red: SLA missed
		}
	}

	// Fixed geometry: 6px per character is a good approximation for the 11px
	// sans-serif used by badge renderers, and reuses shields' own proportions.
	labelW := 6*len(label) + 10
	valueW := 6*len(value) + 10
	totalW := labelW + valueW

	esc := func(s string) string {
		return strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;").Replace(s)
	}

	var b strings.Builder
	fmt.Fprintf(&b, `<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="20" role="img" aria-label="%s: %s">`,
		totalW, esc(label), esc(value))
	b.WriteString(`<title>` + esc(label) + `: ` + esc(value) + `</title>`)
	b.WriteString(`<linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient>`)
	b.WriteString(`<clipPath id="r"><rect width="` + strconv.Itoa(totalW) + `" height="20" rx="3" fill="#fff"/></clipPath>`)
	b.WriteString(`<g clip-path="url(#r)">`)
	b.WriteString(`<rect width="` + strconv.Itoa(labelW) + `" height="20" fill="#555"/>`)
	b.WriteString(`<rect x="` + strconv.Itoa(labelW) + `" width="` + strconv.Itoa(valueW) + `" height="20" fill="` + color + `"/>`)
	b.WriteString(`<rect width="` + strconv.Itoa(totalW) + `" height="20" fill="url(#s)"/>`)
	b.WriteString(`</g>`)
	b.WriteString(`<g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">`)
	fmt.Fprintf(&b, `<text x="%d" y="15" fill="#010101" fill-opacity=".3">%s</text>`, labelW/2, esc(label))
	fmt.Fprintf(&b, `<text x="%d" y="14">%s</text>`, labelW/2, esc(label))
	fmt.Fprintf(&b, `<text x="%d" y="15" fill="#010101" fill-opacity=".3">%s</text>`, labelW+valueW/2, esc(value))
	fmt.Fprintf(&b, `<text x="%d" y="14">%s</text>`, labelW+valueW/2, esc(value))
	b.WriteString(`</g></svg>`)
	return b.String()
}

// ---- small formatting helpers ----------------------------------------------

func formatTimePtr(t *time.Time) string {
	if t == nil {
		return ""
	}
	return t.UTC().Format(time.RFC3339)
}

// formatSeconds renders a duration for humans, keeping seconds for short
// outages and switching to minutes/hours once that reads better.
func formatSeconds(seconds float64) string {
	if seconds <= 0 {
		return "0s"
	}
	d := time.Duration(seconds * float64(time.Second))
	switch {
	case d < time.Minute:
		return fmt.Sprintf("%.0fs", d.Seconds())
	case d < time.Hour:
		return fmt.Sprintf("%.1fm", d.Minutes())
	default:
		return fmt.Sprintf("%.1fh", d.Hours())
	}
}

func slaVerdict(m store.MonthlySLA) string {
	switch {
	case !m.HasData():
		return "no data for this period"
	case m.OngoingOutage:
		return "DEGRADED — incident still open at the last check"
	case m.UptimePct >= 99.9:
		return "MET — uptime at or above 99.9%"
	case m.UptimePct >= 99.0:
		return "AT RISK — uptime above 99% but below the 99.9% target"
	default:
		return "MISSED — uptime below 99%"
	}
}
