name: Integration Tests
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    types: [labeled]

jobs:
  test:
    if: github.event.label.name == 'run-integration' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Integration Tests
        run: cd tests/integration && make integration-test
