// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/sorolens/sorolens/apps/api/internal/store"
)

type ContractConnection struct {
	Nodes    []store.Contract `json:"nodes"`
	PageInfo *PageInfo        `json:"pageInfo"`
}

type MonitoredContractConnection struct {
	Nodes    []store.MonitoredContract `json:"nodes"`
	PageInfo *PageInfo                 `json:"pageInfo"`
}

type PageInfo struct {
	// Opaque cursor for the next page; null on the last page.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type Query struct {
}
