package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/sorolens/sorolens/apps/api/internal/store"
)

// Contract is the resolver for the contract field.
func (r *alertResolver) Contract(ctx context.Context, obj *store.ContractAlert) (*store.Contract, error) {
	return For(ctx).Contract.Load(ctx, obj.ContractID)
}

// Monitor is the resolver for the monitor field.
func (r *alertResolver) Monitor(ctx context.Context, obj *store.ContractAlert) (*store.MonitoredContract, error) {
	return For(ctx).Monitor.Load(ctx, obj.ContractID)
}

// Events is the resolver for the events field.
func (r *contractResolver) Events(ctx context.Context, obj *store.Contract, first *int, typeArg *string) ([]store.Event, error) {
	return For(ctx).Events.Load(ctx, eventsKey{ContractID: obj.ID, Type: deref(typeArg), Limit: limit(first, 20)})
}

// Invocations is the resolver for the invocations field.
func (r *contractResolver) Invocations(ctx context.Context, obj *store.Contract, first *int, status *string, functionName *string) ([]store.Invocation, error) {
	return For(ctx).Invocations.Load(ctx, invocationsKey{
		ContractID:   obj.ID,
		Status:       deref(status),
		FunctionName: deref(functionName),
		Limit:        limit(first, 20),
	})
}

// Storage is the resolver for the storage field.
func (r *contractResolver) Storage(ctx context.Context, obj *store.Contract, first *int, durability *string, status *string) ([]store.StorageEntry, error) {
	return For(ctx).Storage.Load(ctx, storageKey{
		ContractID: obj.ID,
		Durability: deref(durability),
		Status:     deref(status),
		Limit:      limit(first, 20),
	})
}

// Stats is the resolver for the stats field.
func (r *contractResolver) Stats(ctx context.Context, obj *store.Contract, window *string) (*store.ContractStats, error) {
	w := deref(window)
	if w == "" {
		w = "24h"
	}
	s, err := For(ctx).Stats.Load(ctx, statsKey{ContractID: obj.ID, Window: w})
	if err != nil {
		return nil, err
	}
	return &s, nil
}

// Monitor is the resolver for the monitor field.
func (r *contractResolver) Monitor(ctx context.Context, obj *store.Contract) (*store.MonitoredContract, error) {
	return For(ctx).Monitor.Load(ctx, obj.ID)
}

// Alerts is the resolver for the alerts field.
func (r *contractResolver) Alerts(ctx context.Context, obj *store.Contract, first *int, severity *string) ([]store.ContractAlert, error) {
	return For(ctx).Alerts.Load(ctx, alertsKey{ContractID: obj.ID, Severity: deref(severity), Limit: limit(first, 20)})
}

// Contract is the resolver for the contract field.
func (r *eventResolver) Contract(ctx context.Context, obj *store.Event) (*store.Contract, error) {
	return For(ctx).Contract.Load(ctx, obj.ContractID)
}

// Contract is the resolver for the contract field.
func (r *invocationResolver) Contract(ctx context.Context, obj *store.Invocation) (*store.Contract, error) {
	return For(ctx).Contract.Load(ctx, obj.ContractID)
}

// HealthChecks is the resolver for the healthChecks field.
func (r *monitoredContractResolver) HealthChecks(ctx context.Context, obj *store.MonitoredContract, first *int) ([]store.HealthCheck, error) {
	return For(ctx).HealthChecks.Load(ctx, healthChecksKey{ContractID: obj.ContractID, Limit: limit(first, 20)})
}

// Alerts is the resolver for the alerts field.
func (r *monitoredContractResolver) Alerts(ctx context.Context, obj *store.MonitoredContract, first *int, severity *string) ([]store.ContractAlert, error) {
	return For(ctx).Alerts.Load(ctx, alertsKey{ContractID: obj.ContractID, Severity: deref(severity), Limit: limit(first, 20)})
}

// Contract is the resolver for the contract field.
func (r *monitoredContractResolver) Contract(ctx context.Context, obj *store.MonitoredContract) (*store.Contract, error) {
	return For(ctx).Contract.Load(ctx, obj.ContractID)
}

// Contracts is the resolver for the contracts field.
func (r *queryResolver) Contracts(ctx context.Context, network *string, status *string, first *int, after *string) (*ContractConnection, error) {
	net, err := resolveNetwork(network)
	if err != nil {
		return nil, err
	}
	cursor, err := decodeCursor(after)
	if err != nil {
		return nil, err
	}
	contracts, next, err := r.Store.ListContracts(ctx, cursor, limit(first, 50), store.ContractFilters{
		Network: net,
		Status:  deref(status),
	})
	if err != nil {
		return nil, err
	}
	// Prime the contract loader so nested back-references (e.g.
	// events { contract }) resolve from memory.
	loaders := For(ctx)
	for i := range contracts {
		loaders.Contract.Prime(contracts[i].ID, &contracts[i])
	}
	if contracts == nil {
		contracts = []store.Contract{}
	}
	return &ContractConnection{Nodes: contracts, PageInfo: &PageInfo{NextCursor: encodeCursor(next)}}, nil
}

// Contract is the resolver for the contract field.
func (r *queryResolver) Contract(ctx context.Context, id string) (*store.Contract, error) {
	return For(ctx).Contract.Load(ctx, id)
}

// Watchdog is the resolver for the watchdog field.
func (r *queryResolver) Watchdog(ctx context.Context) (*Watchdog, error) {
	return &Watchdog{}, nil
}

// Stats is the resolver for the stats field.
func (r *watchdogResolver) Stats(ctx context.Context, obj *Watchdog, network *string) (*store.WatchdogStats, error) {
	net, err := resolveNetwork(network)
	if err != nil {
		return nil, err
	}
	s, err := r.Store.GetWatchdogStats(ctx, net)
	if err != nil {
		return nil, err
	}
	return &s, nil
}

// Alerts is the resolver for the alerts field.
func (r *watchdogResolver) Alerts(ctx context.Context, obj *Watchdog, severity *string, network *string, first *int) ([]store.ContractAlert, error) {
	net, err := resolveNetwork(network)
	if err != nil {
		return nil, err
	}
	alerts, err := r.Store.ListAlerts(ctx, "", deref(severity), net, limit(first, 50))
	if err != nil {
		return nil, err
	}
	if alerts == nil {
		alerts = []store.ContractAlert{}
	}
	return alerts, nil
}

// Contracts is the resolver for the contracts field.
func (r *watchdogResolver) Contracts(ctx context.Context, obj *Watchdog, network *string, first *int, after *string) (*MonitoredContractConnection, error) {
	net, err := resolveNetwork(network)
	if err != nil {
		return nil, err
	}
	cursor, err := decodeCursor(after)
	if err != nil {
		return nil, err
	}
	items, next, err := r.Store.ListMonitoredContracts(ctx, cursor, limit(first, 50), net)
	if err != nil {
		return nil, err
	}
	loaders := For(ctx)
	for i := range items {
		loaders.Monitor.Prime(items[i].ContractID, &items[i])
	}
	if items == nil {
		items = []store.MonitoredContract{}
	}
	return &MonitoredContractConnection{Nodes: items, PageInfo: &PageInfo{NextCursor: encodeCursor(next)}}, nil
}

// Alert returns AlertResolver implementation.
func (r *Resolver) Alert() AlertResolver { return &alertResolver{r} }

// Contract returns ContractResolver implementation.
func (r *Resolver) Contract() ContractResolver { return &contractResolver{r} }

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// Invocation returns InvocationResolver implementation.
func (r *Resolver) Invocation() InvocationResolver { return &invocationResolver{r} }

// MonitoredContract returns MonitoredContractResolver implementation.
func (r *Resolver) MonitoredContract() MonitoredContractResolver {
	return &monitoredContractResolver{r}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Watchdog returns WatchdogResolver implementation.
func (r *Resolver) Watchdog() WatchdogResolver { return &watchdogResolver{r} }

type (
	alertResolver             struct{ *Resolver }
	contractResolver          struct{ *Resolver }
	eventResolver             struct{ *Resolver }
	invocationResolver        struct{ *Resolver }
	monitoredContractResolver struct{ *Resolver }
	queryResolver             struct{ *Resolver }
	watchdogResolver          struct{ *Resolver }
)
